// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dbtrans.siteModel;

#nullable disable

namespace dbtrans.Migrations
{
    [DbContext(typeof(SQliteCdbSchemaContext))]
    partial class SQliteCdbSchemaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("dbtrans.siteModel.CodelistTableInfoView", b =>
                {
                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChildTableId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ChildTableID");

                    b.Property<string>("ChildTableName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildTableUsername")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateModified")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Oid")
                        .HasColumnType("TEXT")
                        .HasColumnName("oid");

                    b.Property<Guid?>("ParentTableId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ParentTableID");

                    b.Property<string>("ParentTableName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentTableUserName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TableId")
                        .HasColumnType("TEXT")
                        .HasColumnName("TableID");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.ToTable("CodelistTableInfoView", (string)null);
                });

            modelBuilder.Entity("dbtrans.siteModel.CodelistValueView", b =>
                {
                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCreated")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateModified")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongStringValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Oid")
                        .HasColumnType("TEXT")
                        .HasColumnName("oid");

                    b.Property<Guid?>("ParentTableId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ParentTableID");

                    b.Property<string>("ParentTableName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentTableUserName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentValueId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ParentValueID");

                    b.Property<string>("ShortStringValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SortIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TableId")
                        .HasColumnType("TEXT")
                        .HasColumnName("TableID");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableUserName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ValueID");

                    b.ToTable("CodelistValueView", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
